# Generated by Django 2.1.7 on 2019-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=25, verbose_name='kategori_adi')),
            ],
            options={
                'db_table': 'Anasayfa',
            },
        ),
        migrations.CreateModel(
            name='hakkinda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkinda', models.TextField(verbose_name='hakkinda')),
            ],
            options={
                'db_table': 'hakkinda',
            },
        ),
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=30, verbose_name='adi ve Soyadi')),
                ('konu', models.CharField(max_length=50, verbose_name='konu')),
                ('ileti', models.CharField(max_length=700, verbose_name='ileti')),
            ],
            options={
                'db_table': 'iletisim',
            },
        ),
    ]
