# Generated by Django 2.1.7 on 2019-05-29 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_photo', models.ImageField(null=True, upload_to='')),
                ('wall_photo', models.ImageField(null=True, upload_to='')),
                ('slogan', models.CharField(max_length=50, null=True, verbose_name='slogan')),
                ('hakkinda', models.CharField(max_length=200, null=True, verbose_name='hakkında')),
                ('icerik_say', models.IntegerField(default=0, verbose_name='İçerik Sayisi')),
                ('begeni_say', models.IntegerField(default=0, verbose_name='Begeni Sayisi')),
                ('profil_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profil',
            },
        ),
    ]
