# Generated by Django 2.1.7 on 2019-05-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0002_auto_20190530_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icerik',
            name='begeni_say',
            field=models.IntegerField(default=0, verbose_name='Begeni Sayisi'),
        ),
    ]
